[package]
name = "runner"
version = "0.1.0"
edition.workspace = true

[dependencies]
util = { path = "../util" }
clap = { version = "4.5.53", features = ["derive"] }
aoc2015 = { path = "../years/2015" }
aoc2016 = { path = "../years/2016" }

[build-dependencies]

